/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type JobStatus = "DEAD" | "PENDING" | "RUNNING" | "SUCCEEDED";

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface DevMailOutbox {
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  subject: string;
  template: string;
  textBody: string;
  toEmail: string;
  token: string | null;
}

export interface IdempotencyKeys {
  createdAt: Generated<Timestamp>;
  expiresAt: Timestamp;
  key: string;
  requestHash: string;
  responseBody: Json | null;
  responseStatus: number | null;
  state: string;
  userId: string;
}

export interface Jobs {
  attempts: Generated<number>;
  createdAt: Generated<Timestamp>;
  dedupeKey: string | null;
  finishedAt: Timestamp | null;
  id: Generated<string>;
  lastError: string | null;
  lockedAt: Timestamp | null;
  lockedBy: string | null;
  maxAttempts: Generated<number>;
  name: string;
  payload: Generated<Json>;
  runAt: Generated<Timestamp>;
  status: Generated<JobStatus>;
  uniqueKey: string | null;
  updatedAt: Generated<Timestamp>;
}

export interface DB {
  devMailOutbox: DevMailOutbox;
  idempotencyKeys: IdempotencyKeys;
  jobs: Jobs;
}
