/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type AccountVisibility = "PRIVATE" | "PUBLIC";

export type ActivitySource = "APPLE_HEALTH" | "FILE_IMPORT" | "GARMIN" | "HEALTH_CONNECT" | "MANUAL" | "STRAVA";

export type AffinitySubject = "CREATOR" | "FORMAT" | "SPORT" | "TOPIC";

export type AuthTokenPurpose = "EMAIL_VERIFICATION" | "PASSWORD_RESET";

export type CommentPermission = "EVERYONE" | "FOLLOWERS" | "NOBODY";

export type ContentVisibility = "FOLLOWERS" | "PRIVATE" | "PUBLIC";

export type CreatorCategory = "BRAND" | "CLUB_OR_TEAM" | "COACH" | "CONTENT_CREATOR" | "PROFESSIONAL_ATHLETE";

export type DataExportStatus = "EXPIRED" | "FAILED" | "PENDING" | "PROCESSING" | "READY";

export type DevicePlatform = "ANDROID" | "IOS" | "WEB";

export type FeedEventType = "ACTIVITY_OPEN" | "BOOKMARK" | "COMMENT" | "FOLLOW" | "IMPRESSION" | "LIKE" | "MEDIA_EXPAND" | "NOT_INTERESTED" | "PROFILE_OPEN" | "SHARE" | "SKIP" | "TOPIC_INTERACTION" | "UNBOOKMARK" | "UNFOLLOW" | "UNLIKE" | "VIDEO_COMPLETE" | "VIDEO_START" | "WATCH_TIME";

export type FeedSurface = "EXPLORE" | "FOLLOWING" | "HOME" | "OTHER" | "POST_DETAIL" | "PROFILE" | "SEARCH" | "TOPIC";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type IntegrationProvider = "APPLE_HEALTH" | "GARMIN" | "HEALTH_CONNECT" | "STRAVA";

export type IntegrationStatus = "CONNECTED" | "NEEDS_REAUTH" | "REVOKED";

export type JobStatus = "DEAD" | "PENDING" | "RUNNING" | "SUCCEEDED";

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type MediaKind = "IMAGE" | "VIDEO";

export type MediaModerationStatus = "APPROVED" | "PENDING" | "REJECTED";

export type MediaPurpose = "AVATAR" | "POST";

export type MediaStatus = "FAILED" | "PENDING_UPLOAD" | "PROCESSING" | "READY" | "REJECTED" | "UPLOADED";

export type MediaVariantKind = "IMAGE_LARGE" | "IMAGE_MEDIUM" | "IMAGE_THUMB" | "POSTER" | "POSTER_THUMB" | "VIDEO_MP4_HIGH" | "VIDEO_MP4_LOW";

export type ModerationActionType = "DISMISS_REPORT" | "HIDE_CONTENT" | "REMOVE_CONTENT" | "RESTORE_CONTENT" | "SET_CREATOR_VERIFICATION" | "SUSPEND_USER" | "UNSUSPEND_USER" | "WARN_USER";

export type ModerationStatus = "CLEAN" | "HIDDEN" | "REMOVED";

export type NotificationType = "COMMENT_REACTION" | "COMMENT_REPLY" | "FOLLOW_ACCEPTED" | "FOLLOW_REQUEST" | "MENTION_COMMENT" | "MENTION_POST" | "MODERATION_ACTION" | "NEW_FOLLOWER" | "POST_COMMENT" | "POST_PUBLISH_FAILED" | "POST_PUBLISHED" | "POST_REACTION";

export type OauthProvider = "APPLE" | "GOOGLE";

export type PostFormat = "ACTIVITY" | "PHOTO" | "TEXT" | "VIDEO";

export type PostOrigin = "ACTIVITY_AUTO" | "AUTHORED";

export type PostStatus = "DRAFT" | "PENDING_MEDIA" | "PUBLISH_FAILED" | "PUBLISHED";

export type PushProvider = "APNS" | "EXPO" | "FCM";

export type ReactionType = "CLAP" | "FIRE" | "LIKE" | "STRONG";

export type RecordType = "BIGGEST_CLIMB" | "FASTEST_10K" | "FASTEST_5K" | "FASTEST_HALF_MARATHON" | "FASTEST_MARATHON" | "LONGEST_DISTANCE" | "LONGEST_DURATION";

export type ReportReason = "COPYRIGHT" | "HARASSMENT" | "HATE_SPEECH" | "IMPERSONATION" | "MINOR_SAFETY" | "MISINFORMATION" | "OTHER" | "PRIVACY_VIOLATION" | "SELF_HARM" | "SEXUAL_CONTENT" | "SPAM" | "UNDISCLOSED_SPONSORSHIP" | "VIOLENCE";

export type ReportSource = "AUTOMATED" | "USER";

export type ReportStatus = "ACTIONED" | "DISMISSED" | "IN_REVIEW" | "OPEN";

export type ReportTargetType = "COMMENT" | "POST" | "USER";

export type RoutePrivacy = "APPROXIMATE" | "FULL" | "HIDDEN" | "TRIMMED";

export type ShareChannel = "COPY_LINK" | "EXTERNAL_APP" | "SYSTEM_SHARE";

export type SpeedDisplay = "NONE" | "PACE_PER_100M" | "PACE_PER_500M" | "PACE_PER_DISTANCE" | "SPEED";

export type SplitType = "INTERVAL" | "KM" | "LAP" | "MILE";

export type SponsorshipType = "AFFILIATE" | "AMBASSADOR" | "GIFTED_PRODUCT" | "PAID_PARTNERSHIP";

export type SportCategory = "ENDURANCE" | "GENERAL" | "STRENGTH";

export type SportRelation = "FOLLOWER" | "PARTICIPANT";

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export type UnitSystem = "IMPERIAL" | "METRIC";

export type UserRole = "ADMIN" | "MODERATOR" | "USER";

export type UserStatus = "ACTIVE" | "PENDING_DELETION" | "SUSPENDED";

export type VerificationStatus = "NONE" | "PENDING" | "VERIFIED";

export interface Activities {
  caloriesKcal: number | null;
  createdAt: Generated<Timestamp>;
  description: Generated<string>;
  distanceM: number | null;
  elapsedTimeS: number;
  elevationGainM: number | null;
  elevationLossM: number | null;
  externalId: string | null;
  id: Generated<string>;
  integrationConnectionId: string | null;
  isRace: Generated<boolean>;
  locationLabel: string | null;
  movingTimeS: number | null;
  routePrivacy: RoutePrivacy;
  source: Generated<ActivitySource>;
  sportKey: string;
  startedAt: Timestamp;
  subtype: string | null;
  timezone: Generated<string>;
  title: string;
  updatedAt: Generated<Timestamp>;
  userId: string;
  visibility: ContentVisibility;
}

export interface ActivityMetrics {
  activityId: string;
  avgCadence: number | null;
  avgHeartRateBpm: number | null;
  avgPowerW: number | null;
  avgSpeedMps: number | null;
  avgTemperatureC: number | null;
  extra: Generated<Json>;
  maxCadence: number | null;
  maxHeartRateBpm: number | null;
  maxPowerW: number | null;
  maxSpeedMps: number | null;
  normalizedPowerW: number | null;
}

export interface ActivityRecords {
  achievedAt: Timestamp;
  activityId: string;
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  previousValue: number | null;
  recordType: RecordType;
  userId: string;
  value: number;
}

export interface ActivityRoutes {
  activityId: string;
  createdAt: Generated<Timestamp>;
  pointCount: number;
  polyline: string;
}

export interface ActivitySplits {
  activityId: string;
  avgHeartRateBpm: number | null;
  avgSpeedMps: number | null;
  distanceM: number | null;
  elapsedTimeS: number;
  elevationDiffM: number | null;
  splitIndex: number;
  splitType: SplitType;
}

export interface AnalyticsWatermarks {
  lastEventId: string | null;
  name: string;
  updatedAt: Generated<Timestamp>;
}

export interface AuthTokens {
  consumedAt: Timestamp | null;
  createdAt: Generated<Timestamp>;
  expiresAt: Timestamp;
  id: Generated<string>;
  purpose: AuthTokenPurpose;
  tokenHash: string;
  userId: string;
}

export interface Blocks {
  blockedId: string;
  blockerId: string;
  createdAt: Generated<Timestamp>;
}

export interface Bookmarks {
  createdAt: Generated<Timestamp>;
  postId: string;
  userId: string;
}

export interface BrandPartnerships {
  brandName: string;
  brandUrl: string | null;
  createdAt: Generated<Timestamp>;
  creatorUserId: string;
  endedOn: string | null;
  id: Generated<string>;
  startedOn: string | null;
  type: SponsorshipType;
}

export interface CommentMentions {
  commentId: string;
  userId: string;
}

export interface CommentReactions {
  commentId: string;
  createdAt: Generated<Timestamp>;
  userId: string;
}

export interface Comments {
  authorId: string;
  body: string;
  createdAt: Generated<Timestamp>;
  deletedAt: Timestamp | null;
  id: Generated<string>;
  moderationStatus: Generated<ModerationStatus>;
  parentId: string | null;
  postId: string;
  reactionCount: Generated<number>;
  replyCount: Generated<number>;
  replyToUserId: string | null;
}

export interface CreatorProfiles {
  category: CreatorCategory;
  contactEmail: string | null;
  createdAt: Generated<Timestamp>;
  tagline: string | null;
  updatedAt: Generated<Timestamp>;
  userId: string;
  verificationStatus: Generated<VerificationStatus>;
  verifiedAt: Timestamp | null;
  verifiedBy: string | null;
  websiteUrl: string | null;
}

export interface DataExports {
  completedAt: Timestamp | null;
  error: string | null;
  expiresAt: Timestamp | null;
  id: Generated<string>;
  requestedAt: Generated<Timestamp>;
  sizeBytes: number | null;
  status: Generated<DataExportStatus>;
  storageKey: string | null;
  userId: string;
}

export interface Devices {
  appVersion: string | null;
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  installId: string;
  lastSeenAt: Generated<Timestamp>;
  name: string | null;
  platform: DevicePlatform;
  pushProvider: PushProvider | null;
  pushToken: string | null;
  pushTokenUpdatedAt: Timestamp | null;
  updatedAt: Generated<Timestamp>;
  userId: string;
}

export interface DevMailOutbox {
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  subject: string;
  template: string;
  textBody: string;
  toEmail: string;
  token: string | null;
}

export interface FeedEvents {
  activityId: string | null;
  clientTs: Timestamp | null;
  createdAt: Generated<Timestamp>;
  eventId: string;
  eventType: FeedEventType;
  feedRequestId: string | null;
  id: Generated<string>;
  origin: string;
  position: number | null;
  postId: string | null;
  subjectUserId: string | null;
  surface: FeedSurface | null;
  topic: string | null;
  userId: string;
  valueMs: number | null;
}

export interface FeedRequests {
  algorithmVersion: string;
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  itemCount: number;
  pageOffset: Generated<number>;
  snapshotId: string | null;
  surface: FeedSurface;
  userId: string;
}

export interface FeedSnapshots {
  algorithmVersion: string;
  createdAt: Generated<Timestamp>;
  expiresAt: Timestamp;
  id: Generated<string>;
  items: Json;
  surface: FeedSurface;
  userId: string;
}

export interface FollowRequests {
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  requesterId: string;
  targetId: string;
}

export interface Follows {
  createdAt: Generated<Timestamp>;
  followeeId: string;
  followerId: string;
}

export interface IdempotencyKeys {
  createdAt: Generated<Timestamp>;
  expiresAt: Timestamp;
  key: string;
  requestHash: string;
  responseBody: Json | null;
  responseStatus: number | null;
  state: string;
  userId: string;
}

export interface ImageAssets {
  aspectRatio: Generated<number | null>;
  height: number;
  mediaId: string;
  width: number;
}

export interface IntegrationConnections {
  accessTokenSealed: string | null;
  createdAt: Generated<Timestamp>;
  externalAccountId: string | null;
  id: Generated<string>;
  lastSyncedAt: Timestamp | null;
  provider: IntegrationProvider;
  refreshTokenSealed: string | null;
  scopes: Generated<string[]>;
  status: Generated<IntegrationStatus>;
  tokenExpiresAt: Timestamp | null;
  updatedAt: Generated<Timestamp>;
  userId: string;
}

export interface Jobs {
  attempts: Generated<number>;
  createdAt: Generated<Timestamp>;
  dedupeKey: string | null;
  finishedAt: Timestamp | null;
  id: Generated<string>;
  lastError: string | null;
  lockedAt: Timestamp | null;
  lockedBy: string | null;
  maxAttempts: Generated<number>;
  name: string;
  payload: Generated<Json>;
  runAt: Generated<Timestamp>;
  status: Generated<JobStatus>;
  uniqueKey: string | null;
  updatedAt: Generated<Timestamp>;
}

export interface LoginThrottles {
  email: string;
  failureCount: Generated<number>;
  lockedUntil: Timestamp | null;
  updatedAt: Generated<Timestamp>;
}

export interface MediaAssets {
  actualSizeBytes: number | null;
  createdAt: Generated<Timestamp>;
  declaredMime: string;
  declaredSizeBytes: number;
  failureCode: string | null;
  failureDetail: string | null;
  id: Generated<string>;
  kind: MediaKind;
  moderationStatus: Generated<MediaModerationStatus>;
  ownerId: string;
  processingStartedAt: Timestamp | null;
  purpose: MediaPurpose;
  readyAt: Timestamp | null;
  status: Generated<MediaStatus>;
  storageKey: string;
  updatedAt: Generated<Timestamp>;
  uploadedAt: Timestamp | null;
  uploadExpiresAt: Timestamp;
}

export interface MediaVariants {
  bitrateKbps: number | null;
  createdAt: Generated<Timestamp>;
  height: number | null;
  id: Generated<string>;
  kind: MediaVariantKind;
  mediaId: string;
  mimeType: string;
  sizeBytes: number;
  storageKey: string;
  width: number | null;
}

export interface ModerationActions {
  action: ModerationActionType;
  actorId: string;
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  metadata: Generated<Json>;
  note: string | null;
  reportId: string | null;
  targetCommentId: string | null;
  targetPostId: string | null;
  targetType: ReportTargetType;
  targetUserId: string | null;
}

export interface NotificationPreferences {
  inApp: Generated<boolean>;
  push: Generated<boolean>;
  type: NotificationType;
  updatedAt: Generated<Timestamp>;
  userId: string;
}

export interface Notifications {
  actorId: string | null;
  commentId: string | null;
  createdAt: Generated<Timestamp>;
  data: Generated<Json>;
  dedupeKey: string | null;
  id: Generated<string>;
  postId: string | null;
  readAt: Timestamp | null;
  recipientId: string;
  type: NotificationType;
}

export interface OauthIdentities {
  createdAt: Generated<Timestamp>;
  email: string | null;
  id: Generated<string>;
  provider: OauthProvider;
  subject: string;
  userId: string;
}

export interface PostMedia {
  createdAt: Generated<Timestamp>;
  mediaId: string;
  ownerId: string;
  position: number;
  postId: string;
}

export interface PostMentions {
  postId: string;
  userId: string;
}

export interface PostReactions {
  createdAt: Generated<Timestamp>;
  postId: string;
  reaction: Generated<ReactionType>;
  userId: string;
}

export interface Posts {
  activityId: string | null;
  authorId: string;
  bookmarkCount: Generated<number>;
  caption: Generated<string>;
  commentCount: Generated<number>;
  commentPermission: Generated<CommentPermission>;
  createdAt: Generated<Timestamp>;
  deletedAt: Timestamp | null;
  format: PostFormat;
  id: Generated<string>;
  mediaCount: Generated<number>;
  moderationStatus: Generated<ModerationStatus>;
  origin: Generated<PostOrigin>;
  publishedAt: Timestamp | null;
  reactionCount: Generated<number>;
  searchTsv: Generated<string | null>;
  shareCount: Generated<number>;
  status: Generated<PostStatus>;
  updatedAt: Generated<Timestamp>;
  visibility: ContentVisibility;
}

export interface PostStats {
  impressions: Generated<number>;
  notInterested: Generated<number>;
  postId: string;
  skips: Generated<number>;
  updatedAt: Generated<Timestamp>;
  videoCompletes: Generated<number>;
  videoStarts: Generated<number>;
  watchTimeMs: Generated<number>;
}

export interface PostTopics {
  postId: string;
  source: string;
  topicId: string;
}

export interface PrivacyZones {
  centerLat: number;
  centerLon: number;
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  label: string;
  radiusM: number;
  userId: string;
}

export interface Profiles {
  accountVisibility: Generated<AccountVisibility>;
  avatarMediaId: string | null;
  bio: Generated<string>;
  createdAt: Generated<Timestamp>;
  discoverable: Generated<boolean>;
  displayName: string;
  followerCount: Generated<number>;
  followingCount: Generated<number>;
  locationLabel: string | null;
  postCount: Generated<number>;
  primarySportKey: string | null;
  updatedAt: Generated<Timestamp>;
  userId: string;
  username: string;
  usernameChangedAt: Timestamp | null;
}

export interface RecommendationEvents {
  feedRequestId: string;
  position: number;
  postId: string;
  reason: string;
  score: number | null;
  signals: Generated<Json>;
}

export interface RefreshTokens {
  createdAt: Generated<Timestamp>;
  expiresAt: Timestamp;
  id: Generated<string>;
  replacedBy: string | null;
  sessionId: string;
  tokenHash: string;
  usedAt: Timestamp | null;
}

export interface Reports {
  createdAt: Generated<Timestamp>;
  details: string | null;
  id: Generated<string>;
  reason: ReportReason;
  reporterId: string | null;
  resolutionNote: string | null;
  resolvedAt: Timestamp | null;
  resolvedBy: string | null;
  snapshot: Generated<Json>;
  source: Generated<ReportSource>;
  status: Generated<ReportStatus>;
  targetCommentId: string | null;
  targetPostId: string | null;
  targetType: ReportTargetType;
  targetUserId: string | null;
}

export interface Sessions {
  createdAt: Generated<Timestamp>;
  deviceId: string | null;
  expiresAt: Timestamp;
  id: Generated<string>;
  ipPrefix: string | null;
  lastSeenAt: Generated<Timestamp>;
  revokedAt: Timestamp | null;
  revokedReason: string | null;
  userAgent: string | null;
  userId: string;
}

export interface Shares {
  channel: ShareChannel;
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  postId: string;
  userId: string;
}

export interface SponsorshipDisclosures {
  brandName: string;
  createdAt: Generated<Timestamp>;
  partnershipId: string | null;
  postId: string;
  type: SponsorshipType;
}

export interface SportPreferences {
  createdAt: Generated<Timestamp>;
  relation: SportRelation;
  sportKey: string;
  userId: string;
}

export interface Sports {
  category: SportCategory;
  createdAt: Generated<Timestamp>;
  key: string;
  label: string;
  sortOrder: number;
  speedDisplay: SpeedDisplay;
  supportsCadence: boolean;
  supportsDistance: boolean;
  supportsElevation: boolean;
  supportsHeartRate: boolean;
  supportsPower: boolean;
  supportsRoute: boolean;
  supportsSplits: boolean;
}

export interface Topics {
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  slug: string;
}

export interface UserAffinities {
  score: number;
  subjectKey: string;
  subjectType: AffinitySubject;
  updatedAt: Generated<Timestamp>;
  userId: string;
}

export interface Users {
  birthDate: string;
  createdAt: Generated<Timestamp>;
  deletionRequestedAt: Timestamp | null;
  deletionScheduledFor: Timestamp | null;
  email: string;
  emailVerifiedAt: Timestamp | null;
  id: Generated<string>;
  lastLoginAt: Timestamp | null;
  passwordChangedAt: Timestamp | null;
  passwordHash: string | null;
  role: Generated<UserRole>;
  status: Generated<UserStatus>;
  suspendedAt: Timestamp | null;
  updatedAt: Generated<Timestamp>;
}

export interface UserSettings {
  autoCreateActivityPost: Generated<boolean>;
  createdAt: Generated<Timestamp>;
  defaultActivityVisibility: Generated<ContentVisibility>;
  defaultCommentPermission: Generated<CommentPermission>;
  defaultPostVisibility: Generated<ContentVisibility>;
  defaultRoutePrivacy: Generated<RoutePrivacy>;
  personalizationEnabled: Generated<boolean>;
  routeTrimMeters: Generated<number>;
  unitSystem: Generated<UnitSystem>;
  updatedAt: Generated<Timestamp>;
  userId: string;
}

export interface VideoAssets {
  aspectRatio: Generated<number | null>;
  audioCodec: string | null;
  bitrateKbps: number | null;
  durationMs: number;
  fps: number | null;
  hasAudio: Generated<boolean>;
  height: number;
  mediaId: string;
  videoCodec: string | null;
  width: number;
}

export interface DB {
  activities: Activities;
  activityMetrics: ActivityMetrics;
  activityRecords: ActivityRecords;
  activityRoutes: ActivityRoutes;
  activitySplits: ActivitySplits;
  analyticsWatermarks: AnalyticsWatermarks;
  authTokens: AuthTokens;
  blocks: Blocks;
  bookmarks: Bookmarks;
  brandPartnerships: BrandPartnerships;
  commentMentions: CommentMentions;
  commentReactions: CommentReactions;
  comments: Comments;
  creatorProfiles: CreatorProfiles;
  dataExports: DataExports;
  devices: Devices;
  devMailOutbox: DevMailOutbox;
  feedEvents: FeedEvents;
  feedRequests: FeedRequests;
  feedSnapshots: FeedSnapshots;
  followRequests: FollowRequests;
  follows: Follows;
  idempotencyKeys: IdempotencyKeys;
  imageAssets: ImageAssets;
  integrationConnections: IntegrationConnections;
  jobs: Jobs;
  loginThrottles: LoginThrottles;
  mediaAssets: MediaAssets;
  mediaVariants: MediaVariants;
  moderationActions: ModerationActions;
  notificationPreferences: NotificationPreferences;
  notifications: Notifications;
  oauthIdentities: OauthIdentities;
  postMedia: PostMedia;
  postMentions: PostMentions;
  postReactions: PostReactions;
  posts: Posts;
  postStats: PostStats;
  postTopics: PostTopics;
  privacyZones: PrivacyZones;
  profiles: Profiles;
  recommendationEvents: RecommendationEvents;
  refreshTokens: RefreshTokens;
  reports: Reports;
  sessions: Sessions;
  shares: Shares;
  sponsorshipDisclosures: SponsorshipDisclosures;
  sportPreferences: SportPreferences;
  sports: Sports;
  topics: Topics;
  userAffinities: UserAffinities;
  users: Users;
  userSettings: UserSettings;
  videoAssets: VideoAssets;
}
